INSERT INTO products (product_name,  department_name)
VALUES  ("Plates 1", "Kitchen"),
        ("Plates 2", "Kitchen"),
        ("Plates 3", "Kitchen"),
        ("Plates 4", "Kitchen"),
        ("Plates 5", "Kitchen"),
        ("Bowls 1", "Kitchen"),
        ("Bowls 2", "Kitchen"),
        ("Bowls 3", "Kitchen"),
        ("Bowls 4", "Kitchen"),
        ("Bowls 5", "Kitchen"),
        ("Cups 1", "Kitchen"),
        ("Cups 2", "Kitchen"),
        ("Cups 3", "Kitchen"),
        ("Cups 4", "Kitchen"),
        ("Cups 5", "Kitchen"),
        ("Silverware 1", "Kitchen"),
        ("Silverware 2", "Kitchen"),
        ("Silverware 3", "Kitchen"),
        ("Silverware 4", "Kitchen"),
        ("Silverware 5", "Kitchen"),

        ("TV 1", "Electronics"),
        ("TV 2", "Electronics"),
        ("TV 3", "Electronics"),
        ("TV 4", "Electronics"),
        ("TV 5", "Electronics"),
        ("Speakers 1", "Electronics"),
        ("Speakers 2", "Electronics"),
        ("Speakers 3", "Electronics"),
        ("Speakers 4", "Electronics"),
        ("Speakers 5", "Electronics"),
        ("Computer 1", "Electronics"),
        ("Computer 2", "Electronics"),
        ("Computer 3", "Electronics"),
        ("Computer 4", "Electronics"),
        ("Computer 5", "Electronics"),
        ("Laptop 1", "Electronics"),
        ("Laptop 2", "Electronics"),
        ("Laptop 3", "Electronics"),
        ("Laptop 4", "Electronics"),
        ("Laptop 5", "Electronics"),

        ("Pet Food 1", "Pets"),
        ("Pet Food 2", "Pets"),
        ("Pet Food 3", "Pets"),
        ("Pet Food 4", "Pets"),
        ("Pet Food 5", "Pets"),
        ("Toy 1", "Pets"),
        ("Toy 2", "Pets"),
        ("Toy 3", "Pets"),
        ("Toy 4", "Pets"),
        ("Toy 5", "Pets"),
        ("Treats 1", "Pets"),
        ("Treats 2", "Pets"),
        ("Treats 3", "Pets"),
        ("Treats 4", "Pets"),
        ("Treats 5", "Pets"),
        ("Collar 1", "Pets"),
        ("Collar 2", "Pets"),
        ("Collar 3", "Pets"),
        ("Collar 4", "Pets"),
        ("Collar 5", "Pets"),

        ("Shirt 1", "Clothing"),
        ("Shirt 2", "Clothing"),
        ("Shirt 3", "Clothing"),
        ("Shirt 4", "Clothing"),
        ("Shirt 5", "Clothing"),
        ("Pants 1", "Clothing"),
        ("Pants 2", "Clothing"),
        ("Pants 3", "Clothing"),
        ("Pants 4", "Clothing"),
        ("Pants 5", "Clothing"),
        ("Shoes 1", "Clothing"),
        ("Shoes 2", "Clothing"),
        ("Shoes 3", "Clothing"),
        ("Shoes 4", "Clothing"),
        ("Shoes 5", "Clothing"),
        ("Hat 1", "Clothing"),
        ("Hat 2", "Clothing"),
        ("Hat 3", "Clothing"),
        ("Hat 4", "Clothing"),
        ("Hat 5", "Clothing"),
        
        ("Couch 1", "Furniture"),
        ("Couch 2", "Furniture"),
        ("Couch 3", "Furniture"),
        ("Couch 4", "Furniture"),
        ("Couch 5", "Furniture"),
        ("Chair 1", "Furniture"),
        ("Chair 2", "Furniture"),
        ("Chair 3", "Furniture"),
        ("Chair 4", "Furniture"),
        ("Chair 5", "Furniture"),
        ("Table 1", "Furniture"),
        ("Table 2", "Furniture"),
        ("Table 3", "Furniture"),
        ("Table 4", "Furniture"),
        ("Table 5", "Furniture"),
        ("Desk 1", "Furniture"),
        ("Desk 2", "Furniture"),
        ("Desk 3", "Furniture"),
        ("Desk 4", "Furniture"),
        ("Desk 5", "Furniture"),
        
        ("Tent 1", "Outdoor"),
        ("Tent 2", "Outdoor"),
        ("Tent 3", "Outdoor"),
        ("Tent 4", "Outdoor"),
        ("Tent 5", "Outdoor"),
        ("Cooler 1", "Outdoor"),
        ("Cooler 2", "Outdoor"),
        ("Cooler 3", "Outdoor"),
        ("Cooler 4", "Outdoor"),
        ("Cooler 5", "Outdoor"),
        ("Camp Chair 1", "Outdoor"),
        ("Camp Chair 2", "Outdoor"),
        ("Camp Chair 3", "Outdoor"),
        ("Camp Chair 4", "Outdoor"),
        ("Camp Chair 5", "Outdoor"),
        ("Sleeping Bag 1", "Outdoor"),
        ("Sleeping Bag 2", "Outdoor"),
        ("Sleeping Bag 3", "Outdoor"),
        ("Sleeping Bag 4", "Outdoor"),
        ("Sleeping Bag 5", "Outdoor"),

        ("Oil 1", "Auto"),
        ("Oil 2", "Auto"),
        ("Oil 3", "Auto"),
        ("Oil 4", "Auto"),
        ("Oil 5", "Auto"),
        ("Fluid 1", "Auto"),
        ("Fluid 2", "Auto"),
        ("Fluid 3", "Auto"),
        ("Fluid 4", "Auto"),
        ("Fluid 5", "Auto"),
        ("Bulb 1", "Auto"),
        ("Bulb 2", "Auto"),
        ("Bulb 3", "Auto"),
        ("Bulb 4", "Auto"),
        ("Bulb 5", "Auto"),
        ("Part 1", "Auto"),
        ("Part 2", "Auto"),
        ("Part 3", "Auto"),
        ("Part 4", "Auto"),
        ("Part 5", "Auto"),

        ("Activewear 1", "Fitness"),
        ("Activewear 2", "Fitness"),
        ("Activewear 3", "Fitness"),
        ("Activewear 4", "Fitness"),
        ("Activewear 5", "Fitness"),
        ("Weights 1", "Fitness"),
        ("Weights 2", "Fitness"),
        ("Weights 3", "Fitness"),
        ("Weights 4", "Fitness"),
        ("Weights 5", "Fitness"),
        ("Weight Bench 1", "Fitness"),
        ("Weight Bench 2", "Fitness"),
        ("Weight Bench 3", "Fitness"),
        ("Weight Bench 4", "Fitness"),
        ("Weight Bench 5", "Fitness"),
        ("Cardio Machine 1", "Fitness"),
        ("Cardio Machine 2", "Fitness"),
        ("Cardio Machine 3", "Fitness"),
        ("Cardio Machine 4", "Fitness"),
        ("Cardio Machine 5", "Fitness");

UPDATE products SET
    price = ((RAND() * 501) + 1),
    quantity_on_hand = (FLOOR(RAND() * 100) + 1),
    nov16_sales = ((RAND() * 2001) + 1),
    dec16_sales = ((RAND() * 2001) + 1),
    jan17_sales = ((RAND() * 2001) + 1),
    feb17_sales = ((RAND() * 2001) + 1),
    mar17_sales = ((RAND() * 2001) + 1),
    apr17_sales = ((RAND() * 2001) + 1),
    may17_sales = ((RAND() * 2001) + 1),
    jun17_sales = ((RAND() * 2001) + 1),
    jul17_sales = ((RAND() * 2001) + 1),
    aug17_sales = ((RAND() * 2001) + 1),
    sep17_sales = ((RAND() * 2001) + 1),
    oct17_sales = ((RAND() * 2001) + 1)
WHERE
    item_id > 0;